site_name: Modul Pembelajaran Politeknik Sampit
theme:
  name: material
  logo: assets/logo.png
copyright: Copyright &copy; 2024 Achmad Afiffudin Nurzein
nav:
  - Home: 'index.md'
  - 'Sistem Basis Data':
    - 'Pengantar Sistem Basis Data': 'sistem-basis-data/01.md'
  - 'Pengembangan Aplikasi Mobile':
    - 'Android'